### PR TITLE
unified text preprocessing method

### LINKED ISSUE #69: Harmonize text preprocessing workflows
Each of the different exploratory directions are using a lot of manual regex-based data cleaning.
We should consolidate that code into a utils file and use consistent prepossessing across all our different approaches.

### PR DESCRIPTION
**Pull request by michaellzc**
- Apply lowercase
- Apply lemmatization
- Remove HTML tags
- Remove punctuations
- Remove stop words from `Spacy` stop word lists

## Notes
Return `None` if detects unsupported language (non-English)

### CODE REVIEW

**Review by willfenton — COMMENTED** [review]
Looks good to me, but not really what I've been working with (CrowdTruth / tag preprocessing) so I won't approve. 
(CrowdTruth requires mainly tag preprocessing, whereas this is more for ticket title / body)

**Comment by ExiaSR** [comment]
> Looks good to me, but not really what I've been working with (CrowdTruth / tag preprocessing) so I won't approve.
> (CrowdTruth requires mainly tag preprocessing, whereas this is more for ticket title / body)

Would you expand on tag preprocessing? What kind of outcome are you looking for?

for example, how to deal with `-` (hypen), non-english words.

**Comment by willfenton** [comment]
Most of the preprocessing I've done has been essentially lowercasing and removing / replacing annoying characters (newlines, carriage returns, colons, etc.) in the tags. That use case doesn't really require stuff like stopword removal. 

It would be nice if the preprocessor was more modular, so we could create our own pipeline from these building blocks essentially.

**Comment by mlopatka** [comment]
- [ ] konantian review 
- [ ] Ana16boo review 
- [ ]  willfenton  review 

Adding a checklist for tracking reviews on the preprocessing pipeline.

**Review by konantian — APPROVED** [review]

**Comment by ExiaSR** [comment]
> Most of the preprocessing I've done has been essentially lowercasing and removing / replacing annoying characters (newlines, carriage returns, colons, etc.) in the tags. That use case doesn't really require stuff like stopword removal.
> 
> It would be nice if the preprocessor was more modular, so we could create our own pipeline from these building blocks essentially.

Please see updated code.

I couldn't seem to find a way to make the preprocessing modular without slowing down the performance. 

The latest change allow user to specify a custom textpipe operation, so you may add your own preprocessing pipeline while keeping the high level interface consistent.

**Review by willfenton — APPROVED** [review]
Looks good to me, just need to format with `black`.

**Review by Ana16boo — APPROVED** [review]
Looks good to me. Covers everything I could think of

**Pull request merged**
